export const CLICK = "click"
export const DBLCLICK = "dblclick"
export const KEY_PRESS = "keypress"
export const LOAD = "load"
export const KEY_DOWN = "keydown"
export const MOUSE_PRESSED = "mousedown"